"""empty message

Revision ID: 9c096887467b
Revises: 57dd3620ab6b
Create Date: 2020-05-10 00:46:27.361335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c096887467b'
down_revision = '57dd3620ab6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'url')
    # ### end Alembic commands ###
